### ISSUE TITLE
mejorar el ícono de batería

### ISSUE THREAD

**Issue by evilenx** [Paul-Anthony-Martinez/CBAT-Crystal#1]
### Propuesta de Mejora:

> Ajustar el tamaño de las barras que representan la capacidad de la batería para mejorar la estética del ícono.

### Problemática: 

> Actualmente, el ícono de batería en este programa parece estar demasiado grande y parece que el tamaño de estas barras podría reducirse o ajustarse para mejorar la apariencia general del ícono.

**Hail Vim**

**Comment by evilenx** [comment]
.=-.                            
      :==================-  +==+=.   :=------------------   
      #%%%%%%%%%%%%%%%%%%*. ----=+=  *%%%%%%%%%%%%%%%%%%*.  
      +****%########%****=  ------=: +*++*%#########%%#+=   
         =##%%%%%%%#%+=.  .---------.  -###%%%%%##%%#*=.    
         +%#%%%%%%%#%++. -=------=-: -#%%#%%%%%#%%#*=:      
         +%#%%%%%%%#%++. ------=-: -#%%##%%%%#%%#*=:        
         +%#%%%%%%%#%++. ----=-: -#@%##%%%%#%%#*=:          
         +%#%%%%%%%#%++. --=-. -#@%##%%%%#%%#*=:            
         +%#%%%%%%%#%++. --. -#@%##%%%%#%%#*=: .=.          
         +%#%%%%%%%#%+=. . -#@%##%%%%#%%#*=: .:-=+=.        
      .- +%#%%%%%%%#%++. -#@%##%%%%#%%#*=: .:=----=+=.      
    .=*- +%#%%%%%%%#%+==#@%##%%%%#%%%*+:  :=--------=+=.    
   =*+-: +%#%%%%%%%#%++@%##%%%###%%#+:  :=------------=+=.  
   :::-: +%#%%%%%%%#%+*##%%%%#%%%*+:  :----------------:.   
     .:: +%#%%%%%%%%%#%%%%%##%+=--. :----------------:.     
       . +%#%%%%%%%%%%%%%##%%=-#%# -=--------------:.       
         +%#%%%%%%%%%%%##%%#+ -++::=---=---=--=--:.         
         +%#%%%%%%%%%##%%#=-.  ..--::::::--::::.            
         +%#%%%%%%%##%%#+: -+##*.-.:+***---+***-::+***=     
         +%#%%%%%##%%#*-. ..#%%-.=:.#%#+*++#%%#++++%%%=     
         +%#%%%##%%#*-. :-.*%%+ =- *%%:.:. #%#.   :%%*      
         +#####%%#*-. .-=.-%%#.-=.-%%+ :. +%%-   .#%%:      
         +%%%%%#*-.  .:-::%%%:.=::%%#    :%%*    +%%+       
         -*++++-.      . *##*:.- +#*+    +**-   .***-       
                         ..::-:-:.                          
                           .:--:.                           
                             .

**Comment by Paul-Anthony-Martinez** [comment]
Podría añadirse un parser para argumentos y recibir uno que asigne el tamaño de la barra

**Comment by Paul-Anthony-Martinez** [comment]
En el último commit se añadieron funcionalidades para hacer parsing de flags y fue incluida la opción `-w` y `--width` para especificar el ancho de la barra.
